EVM pallet
substrate-developer-hub/docs-sandbox pull request #7
Opened 2021-11-23 20:02 UTC by Eve-Parity

Took EVM content from the legacy `runtime/smart-contracts.md` file and added it to its own topic.

2021-11-25 10:16 UTC, NukeManDan requested changes
ink and contracts pallet should be separate from frontier and evm.

2021-11-25 10:16 UTC, NukeManDan commented on source/docs/main-docs/05-design/evm-pallet.md
> +### How do I run tests?
why is ink in here? this is explicitly different than frontier and EVM, should live in its own page and cross reference each other

2021-11-25 14:38 UTC, sacha-l commented on source/docs/main-docs/05-design/evm-pallet.md
> +### How do I run tests?
Yes -- to add to Dan's point: the EVM pallet has nothing to do with writing smart contracts (and thereby, tests). All it's used for is to execute smart contracts that compile to EVM byte code.

2021-11-26 17:20 UTC, sacha-l approved these changes
Youpeee - one step closer to the finish line 🏁

2021-11-26 18:15 UTC, Eve-Parity commented
I'm a bit concerned with some mixed messages in this content. At one point we note that EVM is not a good idea in production using modern equipment, yet we're explaining how to use it. Can I get some clarification on this @NukeManDan @sacha-l ?

2021-11-29 20:16 UTC, shawntabrizi commented
> At one point we note that EVM is not a good idea in production using modern equipment

I think you may be misinterpreting the comment about 256 bit integers. It was a decision made about the EVM which absolutely an overhead decision when running on mainly 32/64 bit architectures, however doesn't mean users shouldn't use it.

EVM is obviously a very useful environment, and there is not much we can do at this point to change how its fundamental architecture is designed.

2022-01-03 14:29 UTC, sacha-l approved these changes

2022-01-03 14:29 UTC, sacha-l commented on source/docs/main-docs/05-design/evm-pallet.md
> +To download Frontier, go to https://github.com/paritytech/frontier.
```suggestion
To use the Frontier node template, go to https://github.com/paritytech/frontier/tree/master/template.
```

2022-01-03 14:31 UTC, sacha-l commented
Merging this as is and will follow-up with a new PR to refactor and reorganize the content here.

2022-01-03 14:31 UTC, merged